//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int id_KhuyenMai { get; set; }
        public string tenKhuyenMai { get; set; }
        public string doiTuongApDung { get; set; }
        public Nullable<double> giaKhuyenMai { get; set; }
        public Nullable<System.DateTime> thoiGianBatDauKM { get; set; }
        public Nullable<System.DateTime> thoiGianKetThucKM { get; set; }
        public string chiTietKhuyenMai { get; set; }
        public string dieuKienApDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
