//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int id_NguoiDung { get; set; }
        public string hoVaTen { get; set; }
        public string emailND { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string dienThoai { get; set; }
        public Nullable<int> soDanhGia { get; set; }
        public string diaChi { get; set; }
        public Nullable<int> soBinhLuan { get; set; }
        public Nullable<int> veDaMua { get; set; }
        public Nullable<int> phimDaXem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
