//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int id_ThanhToan { get; set; }
        public Nullable<int> id_Ve { get; set; }
        public Nullable<double> tongTien { get; set; }
        public string phuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> thoiGianThanhToan { get; set; }
    
        public virtual Ve Ve { get; set; }
    }
}
