//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
            this.ThanhToans = new HashSet<ThanhToan>();
            this.Ve_BapNuoc = new HashSet<Ve_BapNuoc>();
        }
    
        public int id_Ve { get; set; }
        public Nullable<int> id_LichChieuPhim { get; set; }
        public Nullable<int> id_Ghe { get; set; }
        public string viTriGhe { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<System.TimeSpan> gioDat { get; set; }
        public string maDat { get; set; }
        public Nullable<double> soTien { get; set; }
        public Nullable<int> id_BapNuoc { get; set; }
        public Nullable<int> id_KhuyenMai { get; set; }
    
        public virtual BapNuoc BapNuoc { get; set; }
        public virtual Ghe Ghe { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LichChieuPhim LichChieuPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve_BapNuoc> Ve_BapNuoc { get; set; }
    }
}
