//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatVePhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve_BapNuoc
    {
        public int id_Ve { get; set; }
        public int id_BapNuoc { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual BapNuoc BapNuoc { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
